spring:
  cache:
    cache-names: 
      - "rate-limit-bucket"
    caffeine:
      spec: "maximumSize=10000,expireAfterAccess=30m"
  cloud:
    aws:
      region:
        static: us-east-1 
      credentials:
        access-key: test-key
        secret-key: test-secret
      dynamodb:
        table-name: test-employee-table
        endpoint: http://localhost:8000
  jpa:
    open-in-view: false
                  
application:
  page:
    size: 8
  cors:
    allowed-origins: "*"
    time: 3600
  employee:
    max-retries: 10
    code:
      length: 10
  rate:
    limit: 20
    refil:
      time: 30s
  endpoints:
    authenticated: "/v1/traces/**, /actuator"
    
settings:
  security:
    generated:
      user: ${ADMIN_USER:gopnik}
      password: ${ADMIN_PASSWORD:123456}
      
management:
  endpoints:
    web:
      base-path: ${ACTUATOR:/actuator}
      exposure:
        include: "*"
    access:
      default: read-only
  endpoint:
    info:
      access: read-only
    health:
      show-details: always
    metrics:
      access: read-only 
    prometheus:
      access: unrestricted 

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  prometheus:
    metrics:
      export:
        enabled: true

jaeger:
  tracing:
    enabled: true
    url: http://jaeger:4317
    ratio: 0.1
    batch: 100
