spring:
  cache:
    cache-names: 
      - "rate-limit-bucket"
    caffeine:
      spec: "maximumSize=10000,expireAfterAccess=30m"
  config:
    activate:
      on-profile: prod
  jpa:
    open-in-view: false
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:dummykey}
        secret-key: ${AWS_SECRET_ACCESS_KEY:dummysecret}
      dynamodb:
        table-name: ${DYNAMODB_TABLE_NAME:employee-dev-table}
        endpoint: ${DYNAMODB_ENDPOINT_OVERRIDE:http://localhost:8001}
          
application:
  page:
    size: ${PAGE_SIZE:10}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    time: ${CORS_TIME:3600}
  employee:
    max-retries: ${CODE_RETRIES:10}
    code:
      length: ${CODE_LENGTH:10}
  rate:
    limit: ${RATE_LIMIT:20}
    refil:
      time: ${REFIL_TIME:30s}
  endpoints:
    authenticated: ${ALLOWED_AUTHENTICATED}

settings:
  security:
    generated:
      user: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD} 
