FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder

WORKDIR /app

COPY pom.xml .

RUN --mount=type=cache,target=/root/.m2 mvn dependency:go-offline -B

COPY src ./src

ENTRYPOINT ["mvn", "-Dtestcontainers Ryuk.disabled=true", "verify"]
