spring:
  cache:
    cache-names: 
      - "rate-limit-bucket"
      - "login-attempt"
      - "register-attempt"
    caffeine:
      spec: 
        rate-limit-bucket: "maximumSize=10000,expireAfterAccess=30m"
        login-attempt: "expireAfterWrite=8m"
        register-attempt: "expireAfterWrite=1d"

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:example}

    # ?ssl=false&sslmode=disable
    # ?ssl=true&sslmode=required

    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000 # 30 minutes (in ms)
      idle-timeout: 600000 # 10 minutes (should be less than maxLifetime)
      connection-timeout: 30000 # 30 seconds
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: "ProdDBPool"
  jpa:
    open-in-view: false 
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    enabled: true
    clean-disabled: true 
    validate-on-migrate: true
    # Always on first run should be false
    baseline-on-migrate: ${FLYWAY_BASELINE-MIGRATION:false} 
    baseline-version: ${FLYWAY_VERSION:1}

# 'm' for minutes, 'h' for hours, 'd' for days
application:
  security:
    secret-key: ${SECURITY_KEY}
    expiration: ${EXPIRATION_KEY:15m}
    refresh-token: ${REFRESH_KEY:7d}
    cookie-name: _adaptative_stored_int
    login:
      attempts: ${LOGIN_ATTEMPTS:8}
  page:
    size: ${PAGE_SIZE:10}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
    time: ${CORS_TIME:3600}
  rate:
    limit: ${RATE_LIMIT:20}
    refil:
      time: ${REFIL_TIME:30S} # Seconds
  front:
    csrf: ${CSRF_ENABLED:true}
  login:
    max:
      attempts: ${LOGIN_ATTEMPTS:5}
    user:
      creation: ${CREATION_LIMIT:3}

settings:
  security:
    generated:
      user: ${ADMIN_USER}
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}


