package com.tom.tools.dynamodb.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDbBean
public class Employee {

	private String employeeId;
	private String firstName;
	private String lastName;
	private String email;
	private Department department;

	@DynamoDbPartitionKey
	@DynamoDbAutoGeneratedUuid
	public String getEmployeeId() {
		return employeeId;
	}

}