[project]
dev_addr = "127.0.0.1:9004" # on windows recomends to change to 8000

site_name = "Security Documentation"
site_description = "Project Documentation"
site_author = "treeofmapple"
copyright = """
Copyright &copy; 2026 The authors @treeofmapple
"""

plugins = [
    "awesome-pages"
]

nav = [
    { "Get started" = "index.md" },
    { "Models" = [
        { "User Model" = "model/user.md" },
        { "Auditable Model" = "model/auditable.md" },
        { "Token Model" = "model/token.md" },
        { "Login History Model" = "model/login_history.md" },
    ]},
    { "Enums" = [
        { "Permission" = "model/permission.md" },
        { "Token Type" = "model/token_type.md" },
        { "Role" = "model/role.md" },
    ]},
    {"Controller" = [
        { "Anonymous Controller" = "controller/anonymous_controller.md" },
        { "User Controller" = "controller/user_controller.md" },
        { "Config Controller" = "controller/config_controller.md" },
    ]},
    {"Service" = [
        { "Authentication Service" = "service/authentication_service.md" },
        { "User Service" = "service/user_service.md" },
    ]},
    {"Logic" = [
        { "Security" = [
            { "Jwt Filter" = "logic/security/jwtfilter.md" },
            { "Jwt Service" = "logic/security/jwtservice.md" },
            { "Key Utils" = "logic/security/keyutils.md" },
        ]},
        { "Auditing" = "logic/auditing.md" },
        { "Caching" = "logic/caching.md" },
        { "Scheduled" = "logic/scheduled.md" },
    ]},
    {"Config" = [
        { "Cors" = "config/cors.md" },
        { "Hazel" = "config/hazel.md" },
        { "Quartz" = "config/quartz.md" },
        { "System Start" = "config/systemstart.md" },
        { "Web Security Config" = "config/websecurity_config.md" },
    ]},
    {"Yml Application Configurations" = [
        { "System Variables" = "variables/system_vars.md" },
    ]},
]

[project.theme]

name = "zensical"
# variant = "classic"
favicon = "images/icons/security.png"

language = "en"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"
