[tools]
maven = "3"

[env]
_.file = ".env"

[tasks.build]
description = "Build the Project Image"
run = "mvn clean package -DskipTests"

[tasks.run]
description = "Run Spring App"
run = "mvn clean spring-boot:run -Dspring-boot.run.arguments='--server.port={{arg(i=0, default=\"8000\")}}'"

[tasks.docker_run]
description = "Run Docker Compose Project"
run = "docker compose up --build -d"

[tasks.docker_stop]
description = "Stop Docker Compose Project"
run = "docker compose down"

[tasks.inside_ollama]
description = "Get inside Ollama Docker"
run = "docker exec -it ollama_3.2 bash"
