package com.tom.stripe.payment.payment.enums;

public enum PaymentStatus {

	PAYMENT_SUCCEEDED, 
	PAYMENT_PROCESSING, 
	PAYMENT_FAILED, 
	PAYMENT_CANCELLED,
	PAYMENT_REFUNDED,
	REQUIRED_ACTION,
	REQUIRES_PAYMENT_METHOD 

}
