spring:
  flyway:
    enabled: false
  jpa:
    show-sql: true

application:
  datasource:
    ds1:
      url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}?currentSchema=books
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: BooksPoolConnection

    ds2:
      url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}?currentSchema=authors
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 6
      minimum-idle: 6
      pool-name: AuthorsConnectionPool

  flyway:
    ds1:
      schema: books
      location: classpath:db/migration/books

    ds2:
      schema: authors
      location: classpath:db/migration/authors

logging:
  level:
    com:
      zaxxer:
        hikari: TRACE
        HikariConfig: DEBUG
