FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests

FROM amazon/aws-lambda-java:21-x86_64

COPY --from=build /app/target/*.jar ${LAMBDA_TASK_ROOT}/application.jar

CMD ["com.tom.vehicle.dynamodb.config.LambdaStreamHandler::handleRequest"]