spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:example}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  cors:
    allowed-origins: "*"