-- V3__insert_sample_employees.sql

INSERT INTO employee (name, email, job_title, phone, image_url, employee_code)
VALUES
('John Doe', 'john.doe@example.com', 'Software Engineer', '555-1234', 'http://example.com/image1.jpg', 'EMP001'),
('Jane Smith', 'jane.smith@example.com', 'Data Scientist', '555-5678', 'http://example.com/image2.jpg', 'EMP002'),
('Michael Johnson', 'michael.johnson@example.com', 'Product Manager', '555-8765', 'http://example.com/image3.jpg', 'EMP003'),
('Emily Davis', 'emily.davis@example.com', 'UX Designer', '555-4321', 'http://example.com/image4.jpg', 'EMP004'),
('Daniel Lee', 'daniel.lee@example.com', 'DevOps Engineer', '555-6543', 'http://example.com/image5.jpg', 'EMP005'),
('Sophia Garcia', 'sophia.garcia@example.com', 'QA Engineer', '555-7890', 'http://example.com/image6.jpg', 'EMP006'),
('Lucas Martin', 'lucas.martin@example.com', 'Software Engineer', '555-1122', 'http://example.com/image7.jpg', 'EMP007'),
('Olivia Brown', 'olivia.brown@example.com', 'Marketing Specialist', '555-3344', 'http://example.com/image8.jpg', 'EMP008'),
('Aiden Harris', 'aiden.harris@example.com', 'Product Designer', '555-5566', 'http://example.com/image9.jpg', 'EMP009'),
('Charlotte Clark', 'charlotte.clark@example.com', 'Business Analyst', '555-6677', 'http://example.com/image10.jpg', 'EMP010'),
('Amelia Lewis', 'amelia.lewis@example.com', 'Project Manager', '555-7788', 'http://example.com/image11.jpg', 'EMP011'),
('Ethan Walker', 'ethan.walker@example.com', 'HR Specialist', '555-8899', 'http://example.com/image12.jpg', 'EMP012'),
('Mia Allen', 'mia.allen@example.com', 'Software Engineer', '555-9900', 'http://example.com/image13.jpg', 'EMP013'),
('Liam Young', 'liam.young@example.com', 'QA Lead', '555-1234', 'http://example.com/image14.jpg', 'EMP014'),
('Ella King', 'ella.king@example.com', 'Data Scientist', '555-2345', 'http://example.com/image15.jpg', 'EMP015'),
('William Scott', 'william.scott@example.com', 'Business Development', '555-3456', 'http://example.com/image16.jpg', 'EMP016'),
('Isabella Adams', 'isabella.adams@example.com', 'Product Manager', '555-4567', 'http://example.com/image17.jpg', 'EMP017'),
('Benjamin Nelson', 'benjamin.nelson@example.com', 'System Architect', '555-5678', 'http://example.com/image18.jpg', 'EMP018'),
('Harper Carter', 'harper.carter@example.com', 'Marketing Manager', '555-6789', 'http://example.com/image19.jpg', 'EMP019'),
('Jack Mitchell', 'jack.mitchell@example.com', 'Sales Engineer', '555-7890', 'http://example.com/image20.jpg', 'EMP020'),
('Amos Perez', 'amos.perez@example.com', 'Security Engineer', '555-8901', 'http://example.com/image21.jpg', 'EMP021'),
('Avery Moore', 'avery.moore@example.com', 'Software Developer', '555-9012', 'http://example.com/image22.jpg', 'EMP022'),
('Scarlett Robinson', 'scarlett.robinson@example.com', 'Data Analyst', '555-0123', 'http://example.com/image23.jpg', 'EMP023'),
('Mason Walker', 'mason.walker@example.com', 'Software Architect', '555-1234', 'http://example.com/image24.jpg', 'EMP024'),
('Elijah Torres', 'elijah.torres@example.com', 'Database Administrator', '555-2345', 'http://example.com/image25.jpg', 'EMP025'),
('Grace Parker', 'grace.parker@example.com', 'Product Designer', '555-3456', 'http://example.com/image26.jpg', 'EMP026'),
('Noah Carter', 'noah.carter@example.com', 'Data Scientist', '555-4567', 'http://example.com/image27.jpg', 'EMP027'),
('Lily Hill', 'lily.hill@example.com', 'Cloud Engineer', '555-5678', 'http://example.com/image28.jpg', 'EMP028'),
('David Green', 'david.green@example.com', 'Web Developer', '555-6789', 'http://example.com/image29.jpg', 'EMP029'),
('Zoe Lopez', 'zoe.lopez@example.com', 'Network Engineer', '555-7890', 'http://example.com/image30.jpg', 'EMP030');
