services:
  basic-api-provider:
    build: .
    container_name: user-front-basic
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${SERVER_PORT}:8000"
    env_file:
      - .env
    
  postgres:
    image: postgres:16.3-alpine
    container_name: user-front_postgresql-database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:5432"

volumes:
  postgres_data:
    driver: local
