services:
  mail:
    image: axllent/mailpit:latest
    container_name: mail-server
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MP_MAX_MESSAGES=500
      - MP_DATABASE=/data/mailpit.db
    volumes:
      - mail_data:/data

volumes:
  mail_data:
