package com.tom.security.hash;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.tom.security.hash.config.CustomBanner;

@SpringBootApplication
public class SecurityHashApplication {

	public static void main(String[] args) {
		SpringApplication app = new SpringApplication(SecurityHashApplication.class);
		app.setBanner(new CustomBanner());
		app.run(args);
	}

	/*
	 * TODO: When generating .pem keys put some code inside to alert the system is a
	 * generated key by itself not an key generated by the user
	 * 
	 */

}
