application:
  cors:
    time: 300
    allowed-origins: "${ALLOWED_ORIGINS:http://localhost:3000}"
  security:
    secret-key: ${SECURITY_KEY}
    expiration: ${EXPIRATION_KEY:15M}
    refresh-token:
      expiration: ${REFRESH_KEY:7D}
